version: '3.9'

networks:
  mvp-orange-squad13_network:

services:
  frontend:
    container_name: app_client
    build: ./client
    ports:
      - 3000:3000
    working_dir: /app-client
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
    networks:
      - mvp-orange-squad13_network

  backend:
    container_name: app_server
    build: ./server
    ports:
      - 3001:3001
    working_dir: /app-server
    volumes: 
      - ./server/src:/app-server/src
      - ./client/src:/app-client/src
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - server/.env  # Carregar variáveis de ambiente do arquivo .env
    environment:
      - APP_PORT=${API_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_HOST=${MYSQL_HOST}
      - DB_PORT=${MYSQL_PORT}
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    networks:
      - mvp-orange-squad13_network

  db:
    image: mysql:5.7.32
    container_name: db
    ports:
      - 3306:3306
    env_file:
      - server/.env  # Carregar variáveis de ambiente do arquivo .env
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    networks:
      - mvp-orange-squad13_network
